### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by lootie** [lstagner/OrbitTomography.jl#5]
Hey there! Looking forward to using this package. 
I'm getting an unsatisfiability error from the Equilibrium package when I try to install. Any hints how to resolve this?
![Screen Shot 2021-06-14 at 4 45 50 PM](https://user-images.githubusercontent.com/20742294/121963745-2ce10200-cd30-11eb-9bb3-9e8eed6d5ae0.png)

**Comment by lstagner** [comment]
This package is still in the development stage and isn't yet ready for general users. You will have to add the unregistered Equilibrium.jl package and probably others in order to use this package.

Also, I'm curious about what your use case as this package is for Energetic Particle research in Tokamaks and your previous work doesn't seem to jive with it. Switching fields?

**Comment by lootie** [comment]
Adding {Equilibrium,GuidingCenterOrbits}.jl to my julia installation resolves the above error (thank you).

I was running a code written by a colleague who made use of interpolation using the polyharmonic.jl code from this repo. A quick cursory search does not reveal a registered package having this functionality, although there are several unregistered codes.

**Comment by lstagner** [comment]
That is literally just one file. `polyharmonic.jl` I would just take that and just add it to your package.

**Comment by lootie** [comment]
Adding your package was a good faith effort to acknowledge your work. I will do that since you've suggested it.

**Comment by lstagner** [comment]
I might just make a new package with just the `PolyHarmonicSpline`

**Comment by lootie** [comment]
If you choose to do that, I'd happily use it.

**Comment by lstagner** [comment]
I went ahead and created [PolyharmonicSplines.jl](https://github.com/lstagner/PolyharmonicSplines.jl). Its currently unregistered but that should change
